name: Docker Build and Push
description: 'Build docker images using Dockerfile in your repository and Push them to Docker Hub'
branding:
  icon: box
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'composite'
  steps:
  - 
    run: |
      bash ${{ github.action_path }}/build.sh
    shell: bash
